Softwareentwicklungswerkzeuge 15.09.2021
importPI19fromDHGE/dhge-pi19-sem5 pull request #22
Opened 2021-09-15 12:23 UTC by RvNovae

Habe an einigen Stellen relativ viel aus dem Skript kopiert ... nicht sonderlich produktiv aber anderen Stellen habs ich etwas gescheiter gemacht 😅

2021-09-15 14:09 UTC, ZeroPointMax requested changes
Vielen Dank für die Mitschrift!

Ich hätte tatsächlich einige Änderungswünsche. Es liegt aber wie immer bei euch, was ihr übernehmen wollt und was nicht. Re-Request, wenn fertig pls ^^

2021-09-15 14:09 UTC, ZeroPointMax commented on SEW-KUSCHE/README.md
> +      - ==> nachträglicher Abgleich / Merge mit anderen Standorten
```suggestion
      - $\rightarrow$ Sperren-freies Arbeiten
      - $\rightarrow$ nachträglicher Abgleich / Merge mit anderen Standorten
```

2021-09-15 14:09 UTC, ZeroPointMax commented on SEW-KUSCHE/README.md
> +  - Alle Sourcen (incl. Makefiles, ...) (auch Icons, ...)
```suggestion
  - Alle Sourcen (incl. Makefiles, Icons, ...)
```

2021-09-15 14:09 UTC, ZeroPointMax commented on SEW-KUSCHE/README.md
> +make automatisiert das Compilieren (großer) Projekte:
```suggestion
`make` automatisiert das Compilieren (großer) Projekte:
```

2021-09-15 14:09 UTC, ZeroPointMax commented on SEW-KUSCHE/README.md
> +- make arbeitet nur nach File-Datum, aber greift nicht auf die File-Inhalte zu ==> Es ist nicht auf C/C++ beschränkt, sondern kann für beliebige Aufgaben verwendet werden, bei denen ein Programm eine
```suggestion
- Es kennt Abhängigkeiten (welcher File braucht zum Bauen welche Input-Files?) $\rightarrow$ Es kann voneinander unabhängige Files parallel compilieren! ($\rightarrow$ schneller!)
- Es kann sich selbst rekursiv aufrufen $\rightarrow$ Es kann Unterverzeichnisse, Teilprojekte, ... erzeugen.
- `make` arbeitet nur nach File-Datum, aber greift nicht auf die File-Inhalte zu $\rightarrow$ Es ist nicht auf C/C++ beschränkt, sondern kann für beliebige Aufgaben verwendet werden, bei denen ein Programm einen Outputfile X aus Inputfiles Y1, ... erzeugt. $\rightarrow$ Es wird nicht nur zum Compilieren verwendet, sondern auch zum Installieren, Aufräumen, Testen, Doku erstellen, .tar-Archiv erstellen, ...
```

2021-09-15 14:09 UTC, ZeroPointMax commented on SEW-KUSCHE/README.md
> +- Entwicklung von GNU
```suggestion
- sollen helfen, portable Software und portable Makefiles zu erstellen
- Entwicklung durch GNU
```

Ich glaube, "durch" ist eindeutiger als "von" ^^

2021-09-15 14:09 UTC, ZeroPointMax commented on SEW-KUSCHE/README.md
> +- gettext ist ein Tool zum Internationalisieren aller Texte in einem Programm
```suggestion
- `configure` führt automatische tests auf dem lokalen System aus, um Probleme und Inkompatiblitäten zu finden
- danach wird ein Makefile generiert und ein C-Headerfile
- dieser C-Headerfile steuert plattformabhängige Code-Strukturen mit Makros
- `libtool` ist ein Tool zum Erzeugen und Linken von Shared Libraries, es soll es auf verschiedenen Plattformen vereinheitlichen
- `gettext` ist ein Tool zum Internationalisieren aller Texte in einem Programm
```

Vor langer Zeit im GNU HQ:

Q: wie nennen wir unser tolles Werkzeug zum Linken von .so Dateien?
A: Ah, yes, `libtool`, genius :D

2021-09-15 14:45 UTC, Steve2955 approved these changes

2021-09-15 14:45 UTC, Steve2955 commented on SEW-KUSCHE/README.md
> +  - Head, Master oder Trunk (aktueller Hauptentwicklungs-Branch)
```suggestion
  - `Head`, `Main` oder `Trunk` (aktueller Hauptentwicklungs-Branch)
```

2021-09-15 14:45 UTC, Steve2955 commented on SEW-KUSCHE/README.md
> +- Automatisches Einfügen von Versionsverwaltungs-Tags (Datum, Version, Autor, ...) in Source-Kommentare.
```suggestion
- Automatisches Einfügen von Versionsverwaltungs-Tags (Datum, Version, Autor, ...) in Source-Kommentare
```

2021-09-15 14:45 UTC, Steve2955 commented on SEW-KUSCHE/README.md
> +  - Aktuell im Open-Source-Bereich: GIT (verteilt, ursprünglich für den Linux-Kernel entwickelt, heute für zehntausende Projekte eingesetzt)
```suggestion
  - Aktuell im Open-Source-Bereich: GIT (verteilt, ursprünglich für den Linux-Kernel entwickelt, heute für die meisten Projekte eingesetzt)
```

2021-09-15 14:45 UTC, Steve2955 commented on SEW-KUSCHE/README.md
> +    - Sonderfall “Three Way Merge”: Nicht zwei Files miteinander abgleichen, sondern die Änderungen zwischen zwei Files in einen dritten File einarbeiten.
```suggestion
    - Sonderfall "Three Way Merge": Nicht zwei Files miteinander abgleichen, sondern die Änderungen zwischen zwei Files in einen dritten File einarbeiten.
```

2021-09-15 14:45 UTC, Steve2955 commented on SEW-KUSCHE/README.md
> +  - “Blame Tool”: Anzeige von Fileinhalt mit Version, Datum, Autor neben jeder Zeile
```suggestion
  - "Blame Tool": Anzeige von Fileinhalt mit Version, Datum, Autor neben jeder Zeile
```

2021-09-15 14:45 UTC, Steve2955 commented on SEW-KUSCHE/README.md
> +  - Legt nicht einspielbare Änderungen zum händischen Nachziehen ab.
```suggestion
- **Diff & Merge:**
  - Vergleicht 2 Dateien / Verzeichnisse
  - Liefert zeilenweise Unterschiede in verschiedenen Formaten
  - Gleicht die Unterschiede wenn möglich automatisch ab
  - Sowohl für die Commandline als auch mit GUI
- **Three Way Merge:**
  - Sonderform, spielt die Unterschiede zweier Dateien / Verzeichnisse in einer dritten Datei / einem dritten Verzeichnis ein
- **Kriterien grafischer Tools:**
  - Zeichenweise grafische Darstellung der Unterschiede in den einzelnen Zeilen
  - Geh zum nächsten / vorigen Unterschied
  - Händisches Einfügen oder Entfernen von Unterschieden per Tastatur und Maus, automatisches Mergen aller konfliktfreien Unterschiede
  - Händische Editierbarkeit der Files
  - Händisches Alignment der Differenzen in der Darstellung
  - Mehrere Vergleiche (ganzer Verzeichnisbaum) gleichzeitig
  - Ignorieren von Zwischenräumen / Leerzeilen / unterschiedlichen Zeilenenden / Groß- und Kleinschreibung
- **patch:**
  - Kleines Tool, um Änderungen in Source-Code-Verzeichnissen einzuspielen. Im wesentlichen die Merge-Seite eines 3-Way-Merge:
  - Bekommt diff-Outputs (d.h. geänderte Zeilen) als Input und spielt die Änderungen in einem lokalen Verzeichnis ein
  - Erkennt geringfügig verschobene Änderungen automatisch
  - Legt nicht einspielbare Änderungen zum händischen Nachziehen ab
```

2021-09-15 14:45 UTC, Steve2955 commented on SEW-KUSCHE/README.md
> +- Es baut genau das neu, was notwendig ist / geändert wurde (und nicht mehr!).
```suggestion
- Es erzeugt intern einen Abhängigkeitsgraph der gewünschten Output-Files von den dazu notwendigen Input-Files
- Es prüft, welche der benötigten Files überhaupt noch fehlen, und vergleicht das File-Datum aller vorhandenen direkt voneinander abhängigen Files (potentielles Problem bei Netz-Laufwerken usw. mit ungenauen Uhren!)
- Es baut genau das neu, was notwendig ist / geändert wurde (und nicht mehr!)
```

2021-09-15 14:45 UTC, Steve2955 commented on SEW-KUSCHE/README.md
> +- jede Befehlszeile muss mit einem ECHTEN tab beginnen
```suggestion
- jede Befehlszeile muss mit einem ECHTEN Tab beginnen
```

2021-09-15 14:45 UTC, Steve2955 commented on SEW-KUSCHE/README.md
> +- ein Tool findet nicht-portable Konstrukte im C/C++ code
```suggestion
- ein Tool findet nicht-portable Konstrukte im C/C++ Code
```

2021-09-15 14:45 UTC, Steve2955 commented on SEW-KUSCHE/README.md
> +///
```suggestion
/// this function does something
```

2021-09-16 11:36 UTC, RvNovae commented on SEW-KUSCHE/README.md
> +  - Datenbank (Vorteil oder Nachteil???) (rein text-basiert ist besser)
Nein, das ist von ihm xd

2021-09-16 11:45 UTC, ZeroPointMax approved these changes

2021-09-16 11:47 UTC, merged