SEW vom 16.09.2021
importPI19fromDHGE/dhge-pi19-sem5 pull request #23
Opened 2021-09-16 15:35 UTC by ZeroPointMax

Und nun zu den Tagesthemen:

- Compiler - worauf Sie beim Kauf achten sollten
- Sparen Sie Zeit mit diesen nützlichen Tools rund um Compiler
- Debugger - wie benutzt man sie?
- `ltrace` und `strace` - Sysadmins hassen diesen Trick

2021-09-16 15:40 UTC, ZeroPointMax commented
Ahja, der VSCode Linter lässt Codeboxen in Ruhe; Github tut das nicht :laughing:

2021-09-16 15:54 UTC, Steve2955 approved these changes
Vielen Dank für die Mitschriften, hab nur ein paar mini-Anmerkungen. Aber für das Makefile würde ich gern ein umfangreicheres Beispiel sehen

2021-09-16 15:54 UTC, Steve2955 commented on SEW-KUSCHE/README.md
> +> Oben genanntes Beispiel ist zwar kürzer als die Musterlösung, hat aber die Konsequenz, dass man bei einer Dateiänderung alles neu kompilieren muss und keine Parallelisierung möglich ist.
```suggestion
```make
all: main html/index.html latex/refman.pdf

hfiles=circ.h color.h graobj.h rect.h

main.o: main.cpp $(hfiles)
        @g++ -c main.cpp

rect.o: rect.cpp $(hfiles)
        @g++ -c rect.cpp
	
circ.o: circ.cpp $(hfiles)
        @g++ -c circ.cpp
	
graobj.o: graobj.cpp $(hfiles)
        @g++ -c graobj.cpp
	
sdlinterf.o: sdlinterf.c $(hfiles)
        @gcc `sdl2-config --cflags` -c sdlinterf.c
	
main: circ.o graobj.o main.o rect.o sdlinterf.o
        @echo Compiling $@
        @g++ -o main circ.o graobj.o main.o rect.o sdlinterf.o `sdl2-config --libs`

Doxyfile:
        @doxygen -g

html/index.html: Doxyfile
        @doxygen &> /dev/null
	
latex/refman.pdf: Doxyfile html/index.html
        @$(MAKE) -C latex &> /dev/null

clean:
        @rm -rf main *.o html latex
```

Ich würde hier eigentlich gern mal ein vollständiges `Makefile` sehen, nachdem wir das bei Günther etwas anders gelernt haben.

**Achtung:** Ich weiß nicht, wie man das hier mit den Suggestions machen kann, aber der Code-Block muss noch geschlossen werden.

2021-09-16 15:54 UTC, Steve2955 commented on SEW-KUSCHE/README.md
> +Praxistipps
```suggestion
**Praxistipps**
```

2021-09-16 15:54 UTC, Steve2955 commented on SEW-KUSCHE/README.md
> +- Keine Kompilate unterschiedliche Compiler zusammenlinken
```suggestion
- Keine Kompilate unterschiedlicher Compiler zusammenlinken
```

2021-09-16 15:54 UTC, Steve2955 commented on SEW-KUSCHE/README.md
> +- Cross-Compiler bauen Code für eine andere Zielplattform
```suggestion
- Cross-Compiler bauen Code für eine andere Zielplattformen
```

2021-09-16 15:54 UTC, Steve2955 commented on SEW-KUSCHE/README.md
> +- Optimierung beim Linken ("Link-time Optimization") - Optimierung über Filegrenzen hinweg
```suggestion
- Optimierung beim Linken ("Link-time Optimization") 
- Optimierung über Filegrenzen hinweg
```

2021-09-16 15:54 UTC, Steve2955 commented on SEW-KUSCHE/README.md
> +- 3 Betriebsmodi
```suggestion
- drei Betriebsmodi
```

2021-09-16 15:54 UTC, Steve2955 commented on SEW-KUSCHE/README.md
> +  - Post mortem Debugging: analysieren einer "Leiche"
```suggestion
  - Post-mortem Debugging: Analysieren einer "Leiche"
```

2021-09-16 15:54 UTC, Steve2955 commented on SEW-KUSCHE/README.md
> +  - wenn Programm und Dump nicht zusammenpassen, wird GDB das anmerken
```suggestion
  - wenn Programm und Dump nicht zusammenpassen, wird `gdb` das anmerken
```

2021-09-16 16:27 UTC, ZeroPointMax commented on SEW-KUSCHE/README.md
> +> Oben genanntes Beispiel ist zwar kürzer als die Musterlösung, hat aber die Konsequenz, dass man bei einer Dateiänderung alles neu kompilieren muss und keine Parallelisierung möglich ist.
Ahja, Codeblöcke und das Suggestion Ding sind so ne Sache...

2021-09-16 16:28 UTC, ZeroPointMax commented on SEW-KUSCHE/README.md
> +- Cross-Compiler bauen Code für eine andere Zielplattform
Da müsste ja das "eine" weg oder?

2021-09-16 16:29 UTC, ZeroPointMax commented on SEW-KUSCHE/README.md
> +- Optimierung beim Linken ("Link-time Optimization") - Optimierung über Filegrenzen hinweg
Bist du sicher? Dann würde ich das einrücken wollen, da sich die Optimierung über Filegrenzen hinweg auf LTO bezieht

2021-09-16 16:41 UTC, ZeroPointMax commented on SEW-KUSCHE/README.md
> +- Optimierung beim Linken ("Link-time Optimization") - Optimierung über Filegrenzen hinweg
Achja, weiß nicht, ob du das mitbekommst, also zur Sicherheit: @Steve2955

2021-09-16 18:07 UTC, Steve2955 commented on SEW-KUSCHE/README.md
> +- Optimierung beim Linken ("Link-time Optimization") - Optimierung über Filegrenzen hinweg
```suggestion
- Optimierung beim Linken ("Link-time Optimization") $\rightarrow$ Optimierung über Filegrenzen hinweg
```
@ZeroPointMax Hast recht, dann lieber so ^^

2021-09-16 18:10 UTC, Steve2955 commented
> Ahja, der VSCode Linter lässt Codeboxen in Ruhe; Github tut das nicht 😆

![image](https://user-images.githubusercontent.com/21085384/133663076-9d15cc5d-dbe5-4c03-8e95-c8b209c4fa6d.png)

@ZeroPointMax Falls du sowas in Zukunft vermeiden willst. Ich hab's immer gern aktiv^^

2021-09-17 06:01 UTC, RvNovae requested changes
Hab noch ein paar Additions. Ansonsten super, danke! :)

2021-09-17 06:05 UTC, RvNovae approved these changes

2021-09-17 06:06 UTC, merged