ABWL 210917 + vscode-markdownlint settings
importPI19fromDHGE/dhge-pi19-sem5 pull request #24
Opened 2021-09-17 07:54 UTC by RvNovae

2021-09-17 17:58 UTC, RvNovae commented on ABWL-LEDER/README.md
> +   - Daten, die während der Projekts erhoben wurden, aufschreiben
```suggestion
  - Daten, die während der Projekts erhoben wurden, aufschreiben
```

2021-09-17 18:00 UTC, RvNovae commented on ABWL-LEDER/README.md
> +   - Gantdiagramm (Meilensteine)
```suggestion
  - Gantdiagramm (Meilensteine)
```

2021-09-17 18:00 UTC, RvNovae commented on ABWL-LEDER/README.md
> +   - Workflow
```suggestion
  - Workflow
```

2021-09-17 18:00 UTC, RvNovae commented on ABWL-LEDER/README.md
> +   - Flussplan
```suggestion
  - Flussplan
```

2021-09-17 18:00 UTC, RvNovae commented on ABWL-LEDER/README.md
> +   - Netzplantechnik (Meilensteine, Ressourcen) $\rightarrow$ Pfeilnetzplan, Notennetzplan
```suggestion
  - Netzplantechnik (Meilensteine, Ressourcen) $\rightarrow$ Pfeilnetzplan, Notennetzplan
```

2021-09-17 18:02 UTC, RvNovae commented
Der linter ist endlich glücklich :D

2021-09-17 18:13 UTC, RvNovae commented
Es gibt allerdings noch ein bisschen ein Problem mit dem vscode linter.

Ungeordnete Listen, die geordneten Listen untergeordnet sind, werden bei 2 spaces vom vscode linter angemeckert, bei 3 spaces nicht. Bei 3 spaces meckert allerdings die linter-action, bei 2 ist die linter-action zufrieden. Jemand eine idee?


![image](https://user-images.githubusercontent.com/11728465/133834800-aa88832c-2ad7-476c-9269-15eadea85bcb.png)

2021-09-17 18:50 UTC, ZeroPointMax commented
Ich schaus mir noch an, versprochen, aber ich möchte kurz anmerken, das die Branch SCHOKO 😂

2021-09-17 18:55 UTC, ZeroPointMax commented
Ah shit Listen mixen mag Markdown nicht

2021-09-17 18:57 UTC, ZeroPointMax commented
Ich committe mal einen potentiellen Fix plus Rechtschreibkorrektur: [Gantt](https://en.wikipedia.org/wiki/Gantt_chart)

2021-09-17 19:01 UTC, ZeroPointMax commented
[räusper](https://www.reddit.com/r/AAAAAAAAAAAAAAAAA/)

2021-09-18 10:19 UTC, RvNovae commented
> Ich schaus mir noch an, versprochen, aber ich möchte kurz anmerken, das die Branch SCHOKO heißt 😂

Boah, das ist mir ja gar nicht aufgefallen haha, geil

2021-09-18 10:59 UTC, RvNovae commented
> [räusper](https://www.reddit.com/r/AAAAAAAAAAAAAAAAA/)

Ja, 3 spaces meckert die linter-action an. Die vscode extension allerdings nicht 😄 
3 spaces werden halt auch vom markdownlint entwickler empfohlen: https://github.com/DavidAnson/markdownlint/issues/20

2021-09-19 08:54 UTC, ZeroPointMax commented
> > [räusper](https://www.reddit.com/r/AAAAAAAAAAAAAAAAA/)
> 
> Ja, 3 spaces meckert die linter-action an. Die vscode extension allerdings nicht 😄
> 3 spaces werden halt auch vom markdownlint entwickler empfohlen: [DavidAnson/markdownlint#20](https://github.com/DavidAnson/markdownlint/issues/20)
> 
> Ich persönlich finde zwei besser (und auch sinnvoller) aber iwi müsste man das dem vscode linter beibringen.

Ja, einen von beiden müsste man anpassen. Ich wäre dafür, VScode zu dressieren...

2021-09-19 09:34 UTC, RvNovae commented
> > > [räusper](https://www.reddit.com/r/AAAAAAAAAAAAAAAAA/)
> > 
> > 
> > Ja, 3 spaces meckert die linter-action an. Die vscode extension allerdings nicht 😄
> > 3 spaces werden halt auch vom markdownlint entwickler empfohlen: [DavidAnson/markdownlint#20](https://github.com/DavidAnson/markdownlint/issues/20)
> > Ich persönlich finde zwei besser (und auch sinnvoller) aber iwi müsste man das dem vscode linter beibringen.
> 
> Ja, einen von beiden müsste man anpassen. Ich wäre dafür, VScode zu dressieren...

Dem stimme ich zu ... ich wüsste nur aktuell nicht, wie.

2021-09-19 10:45 UTC, ZeroPointMax approved these changes
Ich auch nicht. Jedenfalls hier schonmal das Approval, fehlt nur noch der blöde Linter....

2021-09-19 18:38 UTC, RvNovae commented
Hatten wir uns nicht auf 2 spaces geeinigt?

2021-09-19 18:54 UTC, ZeroPointMax commented
> Hatten wir uns nicht auf 2 spaces geeinigt? @ZeroPointMax

ich habe nur rumprobiert, in der Hoffnung, dass *irgendwas* hilft

2021-09-19 18:56 UTC, RvNovae commented
> > Hatten wir uns nicht auf 2 spaces geeinigt? @ZeroPointMax
> 
> ich habe nur rumprobiert, in der Hoffnung, dass _irgendwas_ hilft

Naja, jetzt scheint auf jeden fall keiner der beiden linter mehr zu meckern :D
Also keine Ahnung, was du gemacht hast, aber jetzt scheints zu gehen haha

2021-09-19 18:58 UTC, ZeroPointMax commented
> Also keine Ahnung, was du gemacht hast

Das wüsste ich auch gerne 😂 

Also ich habe deinen Inhalt abgeschrieben und händisch eine neue unordered list gemacht und dabei die Tab-Taste 1x gedrückt (um Kusche zu zitieren: "EIN ECHTER Tab!"). Danach die alte nummerierte Liste gelöscht. Dann war alles jut xD

2021-09-19 19:06 UTC, ZeroPointMax commented
@Steve2955 @nukerxy @photovoltex bitte um Review, es geht jetzt :D

2021-09-19 19:41 UTC, photovoltex requested changes
vielen Dank^^
LGTM (neben den Anmerkungen)

2021-09-19 19:41 UTC, photovoltex commented on ABWL-LEDER/README.md
> +- Kausalitäten von Ursachen werden dargestellen
```suggestion
- Kausalitäten von Ursachen werden dargestellt
```

2021-09-19 19:41 UTC, photovoltex commented on ABWL-LEDER/README.md
> +- Erfordert Diziplin und Vereinfachung, damit das Diagramm nutzbar bleibt
```suggestion
- Erfordert Disziplin und Vereinfachung, damit das Diagramm nutzbar bleibt
```

2021-09-19 19:41 UTC, photovoltex commented on ABWL-LEDER/README.md
> +    2. Rangordnunug, Rollen festlegen $\rightarrow$ Storming
```suggestion
    2. Rangordnung, Rollen festlegen $\rightarrow$ Storming
```

2021-09-19 19:41 UTC, photovoltex commented on ABWL-LEDER/README.md
> +    5. Verarbschiedung, Auflösung $\rightarrow$ Adjourning
```suggestion
    5. Verabschiedung, Auflösung $\rightarrow$ Adjourning
```

2021-09-19 21:44 UTC, photovoltex approved these changes
LGTM

2021-09-19 23:03 UTC, merged