E-Commerce 23.09.2021
importPI19fromDHGE/dhge-pi19-sem5 pull request #33
Opened 2021-09-23 09:51 UTC by RvNovae

2021-09-23 13:19 UTC, Steve2955 requested changes
Vielen Dank für die Mitschriften. Hier und da konnte ich noch ein bisschen was ergänzen.

2021-09-23 13:19 UTC, Steve2955 commented on WEB-MUELLER/README.md
> +  - Lichtbildner, Tonträgerhersteller, Filmhersteller, Datenbankhersteller
```suggestion
  - Lichtbilder, Tonträgerhersteller, Filmhersteller, Datenbankhersteller
```

2021-09-23 13:19 UTC, Steve2955 commented on WEB-MUELLER/README.md
> +  - Freistellungsklausel (zum Schutz des Rechteerwerbers, wird von der Haftung gegenüber Vertragspartner freigestellt, falls Rechtegeber die Rechte eigentlich gar nicht hat)
```suggestion
**Vertragsinhalt:**

- Vertragspartner
- Welche Rechte
- Nutzungsarten, Zeitraum, Gebiet
- Garantie über Rechtsinhaberschaft und keine anderweitige Rechtseinräumung
- Freistellungsklausel (zum Schutz des Rechteerwerbers, wird von der Haftung gegenüber Vertragspartner freigestellt, falls Rechtegeber die Rechte eigentlich gar nicht hat)
```

2021-09-23 13:19 UTC, Steve2955 commented on WEB-MUELLER/README.md
> +- **Schrankenregelungen:**
```suggestion
- **Schrankenregelungen §§44a ff. UrhG, insbesondere:**
```

2021-09-23 13:19 UTC, Steve2955 commented on WEB-MUELLER/README.md
> +  - Vervielfältigung zum privaten und sonstigen eigenen Gebrauch §53 UrhG, aber: Vergütungsanspruch §54 UrhG
```suggestion
  - Vervielfältigung zum privaten und sonstigen eigenen Gebrauch §53 UrhG, aber: Vergütungsanspruch §54 UrhG  (Leermittelabgabe)
```

2021-09-23 13:19 UTC, Steve2955 commented on WEB-MUELLER/README.md
> +  - Zitierfreiheit §51 UrhG, aber: Quellenangabe §63 UrhG
```suggestion
  - Zitierfreiheit §51 UrhG, aber: Quellenangabe §63 UrhG (*Bilder sind in der Regel keine Zitate!*)
```

2021-09-23 13:19 UTC, Steve2955 commented on WEB-MUELLER/README.md
> +  - öffentliche Zugänglichmachung für Unterricht und Forschung, §52 a UrhG, aber: Vergütungsanspruch und Quellenangabe
```suggestion
  - öffentliche Zugänglichmachung für Unterricht und Forschung, §52a UrhG, aber: Vergütungsanspruch und Quellenangabe
```

2021-09-23 13:19 UTC, Steve2955 commented on WEB-MUELLER/README.md
> +### Spam - Begriff
```suggestion
## Wettbewerbsrecht

### Spam - Begriff
```
Ich bin der Meinung, dass war die Einleitung zum Wettbewerbsrecht

2021-09-23 13:19 UTC, Steve2955 commented on WEB-MUELLER/README.md
> +- opt-in Modell: Nutzer muss vorher einwilligen
```suggestion
- opt-in Modell: Nutzer muss **vorher** einwilligen
```

2021-09-23 13:19 UTC, Steve2955 commented on WEB-MUELLER/README.md
> +- Newsletter: Eintrag in die Mailingliste + Rückbestätigung + Jederzeitige Möglichkeit der Untersagung zu Basistarifen + Klar und deutlicher Hinweis bei jeder Nutzung auf die Möglichkeit der Untersag
```suggestion
- **Newsletter:** Eintrag in die Mailingliste und Rückbestätigung
  - jederzeitige Möglichkeit der Untersagung zu Basistarifen
  - klar und deutlicher Hinweis bei jeder Nutzung auf die Möglichkeit der Untersagung
```

2021-09-23 13:19 UTC, Steve2955 commented on WEB-MUELLER/README.md
> +
```suggestion

> Verletzungen der Informationspflichten sind auch Verletzungen des Wettbewerbsrecht (unlauterer Wettbewerb)

```

2021-09-23 13:19 UTC, Steve2955 commented on WEB-MUELLER/README.md
> +  - geschäftsmäßige Telemedien (die müssen das Gesetz beachten)
```suggestion
- Adressaten: geschäftsmäßige Telemedien (die müssen das Gesetz beachten)
```

2021-09-23 13:19 UTC, Steve2955 commented on WEB-MUELLER/README.md
> +  - Telefonnummer "schnelle unmittelbare Kommunikation"
```suggestion
  - Telefonnummer: *"schnelle unmittelbare Kommunikation"*
```

2021-09-23 13:19 UTC, Steve2955 commented on WEB-MUELLER/README.md
> +  - Angaben nach HGB/GmbHG/AG auch für E-Mails
```suggestion
- "Geschäftsbrief" $\rightarrow$ Angaben nach HGB/GmbHG/AG auch für E-Mails
```

2021-09-23 13:19 UTC, Steve2955 commented on WEB-MUELLER/README.md
> +$\rightarrow$ [Impressums-Generator](https://wwww.e-recht24.de/impressum-generator.html)
```suggestion
> Empfehlung: [Impressums-Generator](https://wwww.e-recht24.de/impressum-generator.html)
>
> Zwei-Klick-Regel: in zwei Klicks muss man von einer beliebigen Seite das Impressum erreichen
```

2021-09-23 13:19 UTC, Steve2955 commented on WEB-MUELLER/README.md
> +- Impressum muss von jeder Seite aus innerhalb von zwei Klicks erreichbar und gut erkennbar sein!
```suggestion
```
würde ich oben gleich mit reinpacken

2021-09-23 13:19 UTC, Steve2955 commented on WEB-MUELLER/README.md
> +  - Unlauterer Wettbewerb i.S. des UWG
```suggestion
**Fehlerhaftes Impressum:**

- Bußgeld bis 50.000 Euro
- Unlauterer Wettbewerb i.S. des UWG
```

2021-09-23 13:19 UTC, Steve2955 commented on WEB-MUELLER/README.md
> +
```suggestion
```
Die Punkte hatten wir oben schon

2021-09-23 13:19 UTC, Steve2955 commented on WEB-MUELLER/README.md
> +- §13 TMG Cookies usw.
```suggestion
  - §13 TMG Cookies usw.
```

2021-09-23 13:19 UTC, Steve2955 commented on WEB-MUELLER/README.md
> +- Regelungen sollten eigentlich im E-Privacy Gesetz stehen $\rightarrow$ noch nicht fertig
```suggestion
- Regelungen sollten eigentlich im E-Privacy Gesetz stehen $\rightarrow$ noch nicht fertig (coming 2023 or later)
```

2021-09-23 13:19 UTC, Steve2955 commented on WEB-MUELLER/README.md
> +  - Richtigkeit
```suggestion
  - Richtigkeit der Daten
```

2021-09-23 13:19 UTC, Steve2955 commented on WEB-MUELLER/README.md
> +  - TOM (Technisch-organisatorische Maßnahmen): Integrität + Vertrauligkeit der Daten
```suggestion
  - TOM (Technisch-organisatorische Maßnahmen): Integrität und Vertraulichkeit der Daten
```

2021-09-23 13:19 UTC, Steve2955 commented on WEB-MUELLER/README.md
> +- TMG §13 Abs. 2 Datenschutzerklärung durch den Kunden
```suggestion
- TMG §13 Abs. 2: Datenschutzerklärung durch den Kunden
- TMG §13 Abs. 3: Anforderung an Softwaresysteme (Trennung und Verschlüsselung der Daten, ...)
```

2021-09-23 13:19 UTC, Steve2955 commented on WEB-MUELLER/README.md
> +- TMG §13 Abs. 1 Datenschutzhinweise an den Kunden
```suggestion
- TMG §13 Abs. 1: Datenschutzhinweise an den Kunden
```

2021-09-23 14:04 UTC, RvNovae commented on WEB-MUELLER/README.md
> +  - öffentliche Zugänglichmachung für Unterricht und Forschung, §52a UrhG, aber: Vergütungsanspruch und Quellenangabe
```suggestion
  - öffentliche Zugänglichmachung für Unterricht und Forschung, §52a UrhG, aber: Vergütungsanspruch und Quellenangabe

```

2021-09-23 14:09 UTC, Steve2955 commented on WEB-MUELLER/README.md
> +  - Lichtbildner, Tonträgerhersteller, Filmhersteller, Datenbankhersteller
Hast recht, das habe ich etwas verpennt 😅

2021-09-24 13:58 UTC, Steve2955 approved these changes

2021-09-25 17:27 UTC, ZeroPointMax approved these changes
keine Anmerkungen 👍

2021-09-25 17:28 UTC, merged