Update README.md
importPI19fromDHGE/dhge-pi19-sem5 pull request #60
Opened 2021-11-02 10:48 UTC by nukerxy

.

2021-11-02 11:34 UTC, Steve2955 commented on RES-GUENTHER/README.md
> +<!-- md2apkg ignore-card -->
Wenn eine Karte keinen Content hat, ist übrigens auch kein ignore nötig

2021-11-03 10:50 UTC, RvNovae approved these changes

2021-11-03 15:15 UTC, Steve2955 approved these changes

2021-11-03 15:15 UTC, nukerxy commented
wait for #61 before merging

2021-11-03 15:18 UTC, ZeroPointMax requested changes
Hätte eine Ergänzun, ansonsten alles gut, vielen Dank ^^

2021-11-03 15:18 UTC, ZeroPointMax commented on RES-GUENTHER/README.md
> +### PIA 03/11/21
```suggestion

#### Was passiert, wenn man in Schleifen forkt

- Kinder forken ebenfalls
- Prozesse vermehren sich potentiell

### PIA 03/11/21
```

2021-11-03 15:24 UTC, ZeroPointMax approved these changes

2021-11-03 17:42 UTC, ZeroPointMax commented
😢

2021-11-06 14:06 UTC, merged