create anki decks for LKF
importPI19fromDHGE/dhge-pi19-sem5 pull request #68
Opened 2021-11-06 16:48 UTC by nukerxy

@Steve2955 könnte man das so machen?
Der Forwardslash muss eigentlich escaped werden, komisch dass das bisher funktioniert 🤔

2021-11-08 06:21 UTC, Steve2955 requested changes
@nukerxy Funktioniert das bei dir?

Bei mir gibt's Syntax-Probleme 🤔 

```bash
-bash: syntax error near unexpected token `('
```

2021-11-08 07:21 UTC, nukerxy commented
https://regex101.com/r/TafLIv/1

2021-11-08 11:14 UTC, RvNovae commented
Also bei mir lokal klappts

2021-11-08 17:14 UTC, nukerxy commented
Es sind die Klammern, aber wie macht man sonst etwas exklusives??

2021-11-09 08:04 UTC, Steve2955 commented on .github/workflows/anki.yml
> +      - run: for f in [A-Z]*[A-Z]-[A-Z]*[A-Z]\/(?:README|appendix\/LKF)\.md; do d=$(echo ${f} | awk -F/ '{print $1}'); md2apkg -o output/${d}.apkg ${f}; done
Vielen Dank. Problem ist halt jetzt nur noch, dass wir je 2x den gleichen Output-Pfad haben 😅 
```
md2apkg -o output/TEST-TESTTEST.apkg ./TEST-TESTTEST/README.md
md2apkg -o output/TEST-TESTTEST.apkg ./TEST-TESTTEST/appendix/LKF.md
```

2021-11-09 08:08 UTC, photovoltex commented on .github/workflows/anki.yml
> +      - run: for f in [A-Z]*[A-Z]-[A-Z]*[A-Z]\/(?:README|appendix\/LKF)\.md; do d=$(echo ${f} | awk -F/ '{print $1}'); md2apkg -o output/${d}.apkg ${f}; done
Oh stimmt... rip... hmm naja sollte nicht wirklich das Problem sein... ich kann nachher mal schauen und würde eine weiteren Vorschlag einreichen^^ (wie hab ich das nicht bedacht lol)

2021-11-09 09:04 UTC, photovoltex commented on .github/workflows/anki.yml
> +      - run: for f in [A-Z]*[A-Z]-[A-Z]*[A-Z]\/(?:README|appendix\/LKF)\.md; do d=$(echo ${f} | awk -F/ '{print $1}'); md2apkg -o output/${d}.apkg ${f}; done
Hab die namen der Variablen auch noch zusätzlich lesbarer gemacht (doku :D)
```suggestion
      - run: |
          for mdPath in $(find . -regextype posix-egrep -regex './[A-Z]*[A-Z]-[A-Z]*[A-Z]/(README|appendix/LKF).md')
          do name=$(echo $mdPath | awk -F/ '{print $2}')
               if [[ $mdPath == *"LKF"* ]]
               then name=$name-LKF
               fi
               md2apkg -o output/${name}.apkg ${mdPath}
          done
```
Mit dieser Anpassung werden LKF Dokumente mit einem `-LKF` versehen (z.B. TEST-TEST und TEST-TEST-LKF). Ist jederzeit anpassbar mit der if Bedingung die das derzeitige `-LKF` appended.

2021-11-09 10:42 UTC, Steve2955 commented on .github/workflows/anki.yml
> +      - run: for f in [A-Z]*[A-Z]-[A-Z]*[A-Z]\/(?:README|appendix\/LKF)\.md; do d=$(echo ${f} | awk -F/ '{print $1}'); md2apkg -o output/${d}.apkg ${f}; done
Danke, sieht gut aus. Ich vertraue einfach mal darauf, dass das funktioniert :)

2021-11-09 10:44 UTC, Steve2955 approved these changes
Ich hoffe die ABWL LKF, die hier noch drin sind, können wir einfach ignorieren 😅

2021-11-09 18:38 UTC, merged