Pld sthinbetween 09112021
importPI19fromDHGE/dhge-pi19-sem5 pull request #78
Opened 2021-11-09 14:23 UTC by sthinbetween

Wie auch bei ABWL hier die Vervollständigung (in diesem Fall Neuanlage) der Mitschriften.

2021-11-11 17:03 UTC, nukerxy commented on PLD-BARIE/README.md
> +  - 2.Stufe: ODER-Verküpfungen
```suggestion
  - 2.Stufe: ODER-Verknüpfungen
```

2021-11-11 17:03 UTC, nukerxy commented on PLD-BARIE/README.md
> +- die LUT werden in SRAM-Zellen hinterlegt und könnend ann durch Ansteuerung der Eingänge ausgelesen werden
```suggestion
- die LUT werden in SRAM-Zellen hinterlegt und könnend dann durch Ansteuerung der Eingänge ausgelesen werden
```

2021-11-11 17:03 UTC, nukerxy commented on PLD-BARIE/README.md
> +> OLMCs können als Eingang, kombinatorischer Ausgang, Tristate-Ausgang, Tristate-Ausgang im Registermodus und als Resgisterausgang konfiguriert werden
```suggestion
> OLMCs können als Eingang, kombinatorischer Ausgang, Tristate-Ausgang, Tristate-Ausgang im Registermodus und als Registerausgang konfiguriert werden
```

2021-11-11 17:03 UTC, nukerxy commented on PLD-BARIE/README.md
> +- einfach interne Verdrahtung $\rightarrow$ Signallaufzeiten vorhersagbarar als bei *FPGA*
```suggestion
- einfach interne Verdrahtung $\rightarrow$ Signallaufzeiten besser vorhersagbar als bei *FPGA*
```

2021-11-11 17:05 UTC, nukerxy approved these changes
danke 🌞

2021-11-13 11:59 UTC, RvNovae requested changes
Habe euch die Tables mal formatiert. Ansonsten schauts von der Formatierung her gut aus.

Siehe #85

2021-11-13 12:54 UTC, RvNovae approved these changes

2021-11-13 13:10 UTC, sthinbetween commented
> 
> 
> Habe euch die Tables mal formatiert. Ansonsten schauts von der Formatierung her gut aus.
> 
> Siehe #85

Danke :)

2021-11-13 13:55 UTC, sthinbetween commented
Rest gibt es morgen Vormittag. Heut nicht mehr so große Lust ;)

2021-11-14 10:31 UTC, sthinbetween commented
@nukerxy würdest du nochmal drüber schauen? Dann kann gern gemergt werden

2021-11-14 10:40 UTC, nukerxy commented on PLD-BARIE/README.md
> +- Konzept zur Erweiterung der basalen Möglichkeiten in VHDL
was neues für mein Wörtbuch!

2021-11-14 11:02 UTC, nukerxy approved these changes

2021-11-14 11:08 UTC, merged