AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
importPI19fromDHGE/dhge-pi19-sem5 pull request #87
Opened 2021-11-13 17:20 UTC by nukerxy

2021-11-13 17:24 UTC, RvNovae commented
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

2021-11-13 17:26 UTC, nukerxy commented on RES-GUENTHER/extra/socket/socket-01-unix.c
> +  //  unlink(SOCKET_NAME);
Das hier war der Übeltäter

2021-11-13 23:45 UTC, nukerxy commented
Learning points: 

- addr in recvfrom ist die Quelladresse, sollte man auch in sendto wieder benutzen
- Unix Datagram != UDP
- manchmal muss das socket file manuell gelöscht werden

Es ist alles eine große Freude, generell.
🙃

2021-11-14 09:23 UTC, Steve2955 commented
> manchmal muss das socket file manuell gelöscht werden

@nukerxy Warum brauchst du überhaupt ein socket file? Diesbezüglich scheint mir deine Lösung etwas umständlich 🤔 

In Zusammenarbeit mit Luis, ist bei mir Folgendes entstanden. Erscheint mir etwas einfacher und übersichtlicher. Weiß nicht, ob du die Source in TG angeschaut hast, deshalb hier nochmal der Code:

```C
/*
Schreiben Sie nun ein Programm (socket-01.c), welches einen Client und
einen Server realisiert (Client/Server Differenzierung per Parameterübergabe)
- Senden Sie vom Client eine Nachricht (z.B. „Hi Server“) an den Server
- Nutzen Sie die entsprechenden Systemaufrufe, insbesondere Sockets
- Verwenden Sie UDP
- Lassen Sie den Server die empfangene Nachricht ausgeben
*/

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netinet/in.h>

#define PORT 3400
#define BUFSIZE 1024

int main(int argc, char *argv[]){
	int sockfd;
	char buffer[BUFSIZE];
	struct sockaddr_in servaddr, cliaddr;

	// Socket erstellen
	if((sockfd = socket(AF_INET, SOCK_DGRAM, 0)) < 0 ) {
		perror("socket creation failed");
		exit(EXIT_FAILURE);
	}

	// Server-Socket konfigurieren
	servaddr.sin_family = AF_INET; // IPv4
	servaddr.sin_addr.s_addr = INADDR_ANY;
	servaddr.sin_port = htons(PORT);

	if(argc == 2 && strcmp(argv[1], "server") == 0) {
		// Server-Socket an Port binden
		if(bind(sockfd, (const struct sockaddr *)&servaddr, sizeof(servaddr)) < 0 ){
			perror("bind failed");
			exit(EXIT_FAILURE);
		}

		printf("Hallo, ich bin der Server.\n");

		int len = sizeof(cliaddr);

		int n = recvfrom(sockfd, (char *)buffer, BUFSIZE, 0, (struct sockaddr *) &cliaddr, &len);
		buffer[n] = '\0';
		printf("Nachricht vom Client: %s\n", buffer);
	}else{
		char *msg = "Hallo Server!";
		// Nachricht an Server-Socket senden
		sendto(sockfd, (const char *) msg, strlen(msg), 0, (const struct sockaddr *) &servaddr, sizeof(servaddr));
		printf("Nachricht gesendet.\n");
	}

	return 0;
}
```

2021-11-14 09:28 UTC, Steve2955 commented
> Unix Datagram != UDP

Interessanter Auszug dazu aus einer [SO-Answer](https://stackoverflow.com/a/60425748/6792590):

> Each protocol family generally has a few similar concepts of how data will be handled on a socket:
> - sequenced, reliable, two-way, connection-based, byte-streams: SOCK_STREAM (what an IP person would call TCP)
> - connectionless, unreliable, datagrams: SOCK_DGRAM (what an IP person would call UDP)
>
> Different address families have different terms for these basic concepts:
> ```text
> ╔═══════════╦══════════════════════════╗
> ║           ║       Socket Type        ║
> ║ Address   ╟────────────┬─────────────╢
> ║ Family    ║ SOCK_DGRAM │ SOCK_STREAM ║ 
> ╠═══════════╬════════════╪═════════════╣
> ║ IPX/SPX   ║ SPX        │ IPX         ║
> ║ NetBIOS   ║ NetBIOS    │ n/a         ║
> ║ IPv4      ║ UDP        │ TCP         ║    <-
> ║ AppleTalk ║ DDP        │ ADSP        ║
> ║ IPv6      ║ UDP        │ TCP         ║    <-
> ║ IrDA      ║ IrLMP      │ IrTTP       ║
> ║ Bluetooth ║ ?          │ RFCOMM      ║
> ╚═══════════╩════════════╧═════════════╝
> ```

2021-11-14 09:30 UTC, nukerxy commented
> > manchmal muss das socket file manuell gelöscht werden
> 
> @nukerxy Warum brauchst du überhaupt ein socket file? Diesbezüglich scheint mir deine Lösung etwas umständlich 🤔 

Ja, habe ich gesehen.
Wir sind ein bisschen falsch abgebogen und nutzen Unix Sockets sockaddr_un 
@Steve2955

2021-11-14 10:10 UTC, nukerxy commented
> > Unix Datagram != UDP

Die Unix-Sockets sind für IPC gedacht. Sie nutzen kein "IP-UDP" (keine Ports).
Es sind verbindungslose Datagramme, aber kein UDP. Unix-Domäne <--> Internetdomäne
z.b. `sockfd = socket(AF_UNIX, SOCK_DGRAM, IPPROTO_UDP)` wird den Fehler `Protocol not supported` werfen.
Mit 0 ("Nimm das beste Standardprotokoll für AF_UNIX, SOCK_DGRAM") statt IPPROTO_UDP lassen sich DGRAM Sockets erstellen.

> Interessanter Auszug dazu aus einer [SO-Answer](https://stackoverflow.com/a/60425748/6792590):
> 
> > Each protocol family generally has a few similar concepts of how data will be handled on a socket:
> > 
> > * sequenced, reliable, two-way, connection-based, byte-streams: SOCK_STREAM (what an IP person would call TCP)
> > * connectionless, unreliable, datagrams: SOCK_DGRAM (what an IP person would call UDP)
> > 
> > Different address families have different terms for these basic concepts:
> > ```
> > ╔═══════════╦══════════════════════════╗
> > ║           ║       Socket Type        ║
> > ║ Address   ╟────────────┬─────────────╢
> > ║ Family    ║ SOCK_DGRAM │ SOCK_STREAM ║ 
> > ╠═══════════╬════════════╪═════════════╣
> > ║ IPX/SPX   ║ SPX        │ IPX         ║
> > ║ NetBIOS   ║ NetBIOS    │ n/a         ║
> > ║ IPv4      ║ UDP        │ TCP         ║    <-
> > ║ AppleTalk ║ DDP        │ ADSP        ║
> > ║ IPv6      ║ UDP        │ TCP         ║    <-
> > ║ IrDA      ║ IrLMP      │ IrTTP       ║
> > ║ Bluetooth ║ ?          │ RFCOMM      ║
> > ╚═══════════╩════════════╧═════════════╝
> > ```

Schöne Tabelle für die Internetdomäne.

2021-11-14 12:38 UTC, Steve2955 commented
> Die Unix-Sockets sind für IPC gedacht. Sie nutzen kein "IP-UDP" (keine Ports).

@nukerxy Danke, das ist nochmal sehr gut zu betonen. Sicher auch absolut korrekt, aber das entspricht trotzdem nicht dem, was Günther in der Aufgabenstellung verlangt hat.

2021-11-14 13:06 UTC, nukerxy commented
> > Die Unix-Sockets sind für IPC gedacht. Sie nutzen kein "IP-UDP" (keine Ports).
> 
> @nukerxy Danke, das ist nochmal sehr gut zu betonen. Sicher auch absolut korrekt, aber das entspricht trotzdem nicht dem, was Günther in der Aufgabenstellung verlangt hat.

Ach darauf wolltest du hinaus?!
Das ist uns gegen Ende auch klar geworden, man beachte die darauffolgenden Aufgaben.
Deshalb heißt die Datei `-unix`
Am Anfang war das nicht klar- da dachten wir DGRAM = UDP, wird schon passen.

> Warum brauchst du überhaupt ein socket file? Diesbezüglich scheint mir deine Lösung etwas umständlich 

klang für mich so, als sei dir der Socket Type nicht aufgefallen


Hoffe jetzt ist alles geklärt 👍

2021-11-15 07:20 UTC, Steve2955 requested changes

2021-11-15 07:20 UTC, Steve2955 commented on RES-GUENTHER/extra/socket/faulty_socket-02-unix.c
> +                goto end;
Eine PR mit `goto` kann ich übrigens prinzipiell nicht mergen 😅

2021-11-15 07:30 UTC, ZeroPointMax commented on RES-GUENTHER/extra/socket/faulty_socket-02-unix.c
> +                goto end;
+1

2021-11-15 09:21 UTC, nukerxy commented on RES-GUENTHER/extra/socket/faulty_socket-02-unix.c
> +                goto end;
🙄

2021-11-15 09:38 UTC, nukerxy commented
Hingepfuschtes socket-02.c, ohne Kommentare 
[gist](https://gist.github.com/nukerxy/3eeea3f90f43d73fdb7019c209dc2494)

2021-11-15 12:45 UTC, RvNovae commented
> > manchmal muss das socket file manuell gelöscht werden
> 
> @nukerxy Warum brauchst du überhaupt ein socket file? Diesbezüglich scheint mir deine Lösung etwas umständlich 🤔
> 
> In Zusammenarbeit mit Luis, ist bei mir Folgendes entstanden. Erscheint mir etwas einfacher und übersichtlicher. Weiß nicht, ob du die Source in TG angeschaut hast, deshalb hier nochmal der Code:
> 
> ```c
> /*
> Schreiben Sie nun ein Programm (socket-01.c), welches einen Client und
> einen Server realisiert (Client/Server Differenzierung per Parameterübergabe)
> - Senden Sie vom Client eine Nachricht (z.B. „Hi Server“) an den Server
> - Nutzen Sie die entsprechenden Systemaufrufe, insbesondere Sockets
> - Verwenden Sie UDP
> - Lassen Sie den Server die empfangene Nachricht ausgeben
> */
> 
> #include <stdio.h>
> #include <stdlib.h>
> #include <unistd.h>
> #include <string.h>
> #include <sys/types.h>
> #include <sys/socket.h>
> #include <arpa/inet.h>
> #include <netinet/in.h>
> 
> #define PORT 3400
> #define BUFSIZE 1024
> 
> int main(int argc, char *argv[]){
> 	int sockfd;
> 	char buffer[BUFSIZE];
> 	struct sockaddr_in servaddr, cliaddr;
> 
> 	// Socket erstellen
> 	if((sockfd = socket(AF_INET, SOCK_DGRAM, 0)) < 0 ) {
> 		perror("socket creation failed");
> 		exit(EXIT_FAILURE);
> 	}
> 
> 	// Server-Socket konfigurieren
> 	servaddr.sin_family = AF_INET; // IPv4
> 	servaddr.sin_addr.s_addr = INADDR_ANY;
> 	servaddr.sin_port = htons(PORT);
> 
> 	if(argc == 2 && strcmp(argv[1], "server") == 0) {
> 		// Server-Socket an Port binden
> 		if(bind(sockfd, (const struct sockaddr *)&servaddr, sizeof(servaddr)) < 0 ){
> 			perror("bind failed");
> 			exit(EXIT_FAILURE);
> 		}
> 
> 		printf("Hallo, ich bin der Server.\n");
> 
> 		int len = sizeof(cliaddr);
> 
> 		int n = recvfrom(sockfd, (char *)buffer, BUFSIZE, 0, (struct sockaddr *) &cliaddr, &len);
> 		buffer[n] = '\0';
> 		printf("Nachricht vom Client: %s\n", buffer);
> 	}else{
> 		char *msg = "Hallo Server!";
> 		// Nachricht an Server-Socket senden
> 		sendto(sockfd, (const char *) msg, strlen(msg), 0, (const struct sockaddr *) &servaddr, sizeof(servaddr));
> 		printf("Nachricht gesendet.\n");
> 	}
> 
> 	return 0;
> }
> ```

Wollen wir das Beispiel mit übernehmen?

2021-11-17 13:55 UTC, nukerxy commented
socket-04: Chatprogramm, UDP, Hardcoded IP
Spoiler: https://gist.github.com/nukerxy/6ef5ce389f63cf073a20a4e3fdbd566a

2021-11-18 11:08 UTC, RvNovae commented
> Spoiler Warnung,socket-04: Chatprogramm, UDP, Hardcoded IP ohne Kommentare
> [Hier entlang](https://gist.github.com/nukerxy/6ef5ce389f63cf073a20a4e3fdbd566a)

Das funktioniert ja echt klasse!
Können wir das direkt mit übernehmen?

2021-11-23 15:28 UTC, RvNovae commented
Wollen wir das Ding mal mergen? Jetzt wo's eh egal ist 😄

2021-11-23 15:49 UTC, ZeroPointMax approved these changes

2021-11-23 15:59 UTC, RvNovae approved these changes

2021-11-23 17:42 UTC, Steve2955 approved these changes

2021-11-23 17:42 UTC, merged