LVS vom 15.11.2021
importPI19fromDHGE/dhge-pi19-sem5 pull request #93
Opened 2021-11-15 16:21 UTC by ZeroPointMax

Hauptsächlich Prüfungsvorbereitung - die Sockets sind ja als Übung vorhanden

2021-11-15 16:31 UTC, ZeroPointMax commented
Siehe auch #90

2021-11-15 21:11 UTC, RvNovae approved these changes

2021-11-16 20:11 UTC, nukerxy requested changes
#90 ist quasi fast fertig, ich prüfe nochmal, dieser PR wird bald closed.
Hab alles rüber gehievt 👍

2021-11-16 20:20 UTC, nukerxy commented
#90

2021-11-16 20:20 UTC, closed without merging